#--- BungeeHostLimiter Config File ---#

Default Host Names:
    - play.vik1395.me
    - mc.vik1395.me
# Enter a list of default host names players can use to log in to your server.
# Leave this empty if you want to only use custom host names.

Custom Host Names:
    md_5: md5.vik1395.me
    Vik1395: Vik1395.vik1395.me
# Enter a list of players and their custom Wildcard Hosts. 
# These players can only login to the server using the given host name.

Default Kick Message: 'You have not entered using a valid IP. Please use one of the following IPs to enter this Server: %list%'
# Enter the kick message shown to default players that log in through an IP not
# listed in the Default Host Names. Use %list% to show the list of IPs they can use.

Custom Kick Message: 'You have not entered using a valid host key!'
# Enter the kick message shown to players who dont join with their custom key.

Enable UUID Mode: false
# Set this to true if you want to use UUIDs instead of player names.
# If you use this, replace player name with their UUID in Custom Host Names like:
# 069a79f444e94726a5befca90e38aaf5: Notch.vik1395.me